"""
NIRCam mask round-trip — .reg files ↔ Supabase ``nircam_exposures.mask_regions``.

The web admin UI ``/admin/nircam/[id]`` is the canonical editing surface for
per-exposure mask polygons. This module materializes that DB state back into
the reduction workspace:

``pull-masks``
    Materializes the DB polygons back into ``<rootname>.reg`` files in DS9
    ``image`` coord format, ready for ``apply_masks_step`` to consume. To
    keep hand-drawn legacy masks safe, the writer only touches files for
    which the matching exposure has a non-null ``mask_regions`` row: a
    .reg without any DB representation is treated as a local-only artifact
    and left alone. The ``_imported/`` archive (left behind by the retired
    one-time ``import-masks`` command, issue #371) is never modified.

Why pixel coords as the canonical DB representation:
    The web canvas is pixel-native and cannot reasonably ship a GWCS-aware
    JS WCS library. Polygons were converted FK5/ICRS → pixel once at import
    time using the actual exposure WCS (with distortion), so the in-browser
    editor can render and edit polygons with zero WCS round-trips, and
    ``apply_masks_step`` reads the materialized ``image``-coord ``.reg``
    as a no-op pixel polygon.
"""

from datetime import datetime, timezone


def _utcnow_iso():
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Pull: DB → .reg
# ---------------------------------------------------------------------------

def pull_masks(field, config, dry_run=False):
    """Write ``mask_regions`` JSONB rows back out as DS9 ``image`` .reg files.

    Only writes files for exposures whose ``mask_regions`` is non-null.
    Legacy ``.reg`` files with no DB representation are left untouched —
    that's the safety net for hand-drawn masks that haven't been imported.

    The materialized file always carries a ``# Generated by ...`` header so
    a human opening the file knows it's a build artifact.
    """
    from campfire.deploy.nircam import _resolve_nircam_dirs
    from campfire.deploy.supabase import get_supabase_client

    dirs = _resolve_nircam_dirs(field)
    masks_root = dirs['masks']

    client = get_supabase_client(config)
    resp = (client.table('nircam_exposures')
            .select('filter,filename,mask_regions')
            .eq('field', field)
            .not_.is_('mask_regions', 'null')
            .execute())
    rows = resp.data or []
    if not rows:
        print(f"No mask_regions rows for field={field}")
        return

    print(f"Field: {field}")
    print(f"Exposures with DB masks: {len(rows)}")

    n_written = 0
    n_empty = 0
    generated_at = _utcnow_iso()
    for row in rows:
        payload = row.get('mask_regions') or {}
        polygons = payload.get('polygons') or []
        if not polygons:
            n_empty += 1
            continue
        filtname = row['filter']
        basename = row['filename']
        out_dir = masks_root / filtname
        out_path = out_dir / f'{basename}.reg'

        content = _serialize_regfile(polygons, generated_at=generated_at)
        if dry_run:
            print(f"  would write {filtname}/{out_path.name} "
                  f"({len(polygons)} polygon"
                  f"{'s' if len(polygons) != 1 else ''})")
            continue

        out_dir.mkdir(parents=True, exist_ok=True)
        tmp_path = out_path.with_suffix(out_path.suffix + '.tmp')
        tmp_path.write_text(content)
        tmp_path.replace(out_path)
        n_written += 1
        print(f"  wrote {filtname}/{out_path.name} ({len(polygons)} "
              f"polygon{'s' if len(polygons) != 1 else ''})")

    if dry_run:
        print(f"\nDry run — no files written. {len(rows) - n_empty} would "
              f"be written, {n_empty} empty.")
    else:
        print(f"\nWrote {n_written}, skipped {n_empty} empty")


def _serialize_regfile(polygons, generated_at):
    """Render a list of polygon dicts as a DS9 image-coord .reg file."""
    lines = [
        '# Region file format: DS9 version 4.1',
        f'# Generated by campfire deploy pull-masks at {generated_at}.',
        '# Manual edits will be overwritten on the next pull.',
        ('global color=green dashlist=8 3 width=1 font="helvetica 10 normal '
         'roman" select=1 highlite=1 dash=0 fixed=0 edit=1 move=1 delete=1 '
         'include=1 source=1'),
        'image',
    ]
    for poly in polygons:
        verts = poly.get('vertices') or []
        if len(verts) < 3:
            continue
        flat = ','.join(f'{float(x):.4f},{float(y):.4f}' for x, y in verts)
        label = poly.get('label')
        suffix = f' # text={{{label}}}' if label else ''
        lines.append(f'polygon({flat}){suffix}')
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Drift report (epic #261, N6, D8): local .reg vs DB masks
# ---------------------------------------------------------------------------

def mask_drift_report(field, config):
    """Diff local ``masks/<filter>/*.reg`` against DB ``mask_regions``; warn.

    Advisory (exit 0). Returns a dict for tests with three categories:

    * ``stale`` — a pull-generated ``.reg`` whose DB row now has no polygons
      (the portal cleared the mask, but ``pull-masks`` only writes non-null rows
      so the file lingers and ``apply_masks`` still applies it).
    * ``local_only`` — a non-generated ``.reg`` for an exposure with no DB mask
      (hand-drawn, never imported — the portal can't see it). Never told to
      delete; it's the safety net for hand-drawn masks.
    * ``not_materialized`` — DB has polygons but no local ``.reg`` (``pull-masks``
      not run yet).
    """
    from campfire.deploy.nircam import _resolve_nircam_dirs
    from campfire.deploy.supabase import get_supabase_client

    dirs = _resolve_nircam_dirs(field)
    masks_root = dirs['masks']

    client = get_supabase_client(config)
    resp = (client.table('nircam_exposures')
            .select('filter,filename,mask_regions')
            .eq('field', field)
            .execute())
    rows = resp.data or []
    db_has_mask = {}
    for row in rows:
        payload = row.get('mask_regions') or {}
        db_has_mask[(row['filter'], row['filename'])] = bool(payload.get('polygons'))

    stale, local_only = [], []
    seen_on_disk = set()
    if masks_root.exists():
        for filt_dir in sorted(masks_root.iterdir()):
            if not filt_dir.is_dir() or filt_dir.name == '_imported':
                continue
            filtname = filt_dir.name
            for reg_path in sorted(filt_dir.glob('*.reg')):
                rootname = reg_path.stem
                seen_on_disk.add((filtname, rootname))
                head = ''
                try:
                    with open(reg_path) as fh:
                        head = ''.join(fh.readline() for _ in range(4))
                except OSError:
                    pass
                is_generated = 'Generated by campfire deploy' in head
                has_db = db_has_mask.get((filtname, rootname), False)
                if is_generated and not has_db:
                    stale.append(str(reg_path))
                elif not is_generated and not has_db:
                    local_only.append(str(reg_path))

    not_materialized = [
        f"{filt}/{root}" for (filt, root), has in sorted(db_has_mask.items())
        if has and (filt, root) not in seen_on_disk
    ]

    print(f"\nMask drift report for field={field}:")
    if not (stale or local_only or not_materialized):
        print("  clean — local .reg files and DB masks agree.")
    for p in stale:
        print(f"  STALE (portal cleared, combine still applies): {p}\n"
              f"        remove it, or re-import if the mask is intentional.")
    for p in local_only:
        print(f"  LOCAL-ONLY (not in DB, portal can't see it): {p}\n"
              f"        redraw it in the portal mask editor to track it in the DB.")
    for k in not_materialized:
        print(f"  DB MASK not on disk (pull not run): {k}\n"
              f"        run: campfire deploy nircam pull-masks --field {field}")

    return {'stale': stale, 'local_only': local_only,
            'not_materialized': not_materialized}

