"""NIRSpec rate-mask pull: DB mask_regions → reference/nirspec/<obs>/masks/*.reg.

The cloud→local half of the rate-mask review loop (design §3.5), the NIRSpec
analogue of ``nircam_masks.pull_masks``. Reads ``nirspec_rate_exposures.mask_regions``
(the jsonb the web editor writes) and materializes each into a DS9 ``image``-coord
``.reg`` file the pipeline reads before stage 2 (``masks.py``). DB-resident: these
files are never registered in ``storage_objects``.

The ``.reg`` filename is ``<exposure_root>_<detector>.reg`` — i.e.
``filename.replace("_rate.fits", ".reg")`` — which equals the pipeline's
``masks._rate_basename(rate_file)`` stem, so the pull-write and the pipeline-read
agree by construction. The DS9 body is produced by the SAME ``_serialize_regfile``
NIRCam uses, so ``masks.hash_mask`` (which strips ``#`` comment lines, incl. the
timestamp header) is stable across re-pulls and only changes when the polygons do.
"""
from __future__ import annotations

from campfire.deploy.nircam_masks import _serialize_regfile, _utcnow_iso
from campfire.deploy.supabase import get_supabase_client


def pull_rate_masks(obs, config, dry_run=False):
    """Write ``nirspec_rate_exposures.mask_regions`` rows out as DS9 ``.reg`` files.

    Only writes files for rows whose ``mask_regions`` is non-null; a row with an
    empty polygon list is skipped (counted). Full overwrite of each written file
    (reversible), atomic tmp-write + replace, with a ``# Generated by ...`` header.
    """
    from campfire_layout import Scope, reference_dir
    from campfire.deploy.nircam import _resolve_campfire_root

    masks_dir = reference_dir('nirspec', Scope(obs=obs), root=_resolve_campfire_root()) / 'masks'

    client = get_supabase_client(config)
    resp = (client.table('nirspec_rate_exposures')
            .select('observation, exposure_root, detector, filename, mask_regions')
            .eq('observation', obs)
            .not_.is_('mask_regions', 'null')
            .execute())
    rows = resp.data or []
    if not rows:
        print(f"No mask_regions rows for observation={obs}")
        return

    print(f"Observation: {obs}")
    print(f"Rate files with DB masks: {len(rows)}")

    n_written = 0
    n_empty = 0
    generated_at = _utcnow_iso()
    for row in rows:
        payload = row.get('mask_regions') or {}
        polygons = payload.get('polygons') or []
        if not polygons:
            n_empty += 1
            continue
        # <exposure_root>_<detector>.reg == filename without the _rate.fits suffix
        # == masks._rate_basename(rate_file). Both forms are equal by construction;
        # use the filename swap so it tracks the rate file exactly.
        reg_name = row['filename'].replace('_rate.fits', '.reg')
        out_path = masks_dir / reg_name

        content = _serialize_regfile(polygons, generated_at=generated_at)
        if dry_run:
            print(f"  would write masks/{reg_name} "
                  f"({len(polygons)} polygon{'s' if len(polygons) != 1 else ''})")
            continue

        masks_dir.mkdir(parents=True, exist_ok=True)
        tmp_path = out_path.with_suffix(out_path.suffix + '.tmp')
        tmp_path.write_text(content)
        tmp_path.replace(out_path)
        n_written += 1
        print(f"  wrote masks/{reg_name} "
              f"({len(polygons)} polygon{'s' if len(polygons) != 1 else ''})")

    if dry_run:
        print(f"\nDry run — no files written. {len(rows) - n_empty} would be "
              f"written, {n_empty} empty.")
    else:
        print(f"\nWrote {n_written}, skipped {n_empty} empty")
