#!/bin/zsh

python scripts/deploy.py --obs capers_cosmos_p1 --json-only
python scripts/deploy.py --obs capers_cosmos_p2 --json-only
python scripts/deploy.py --obs capers_cosmos_p3 --json-only
python scripts/deploy.py --obs capers_cosmos_p4 --json-only
python scripts/deploy.py --obs capers_cosmos_p5 --json-only
python scripts/deploy.py --obs capers_cosmos_p6 --json-only
python scripts/deploy.py --obs capers_cosmos_p7 --json-only
python scripts/deploy.py --obs capers_egs_p1 --json-only
python scripts/deploy.py --obs capers_egs_p2 --json-only
python scripts/deploy.py --obs capers_egs_p3 --json-only
python scripts/deploy.py --obs capers_egs_p4 --json-only
python scripts/deploy.py --obs capers_egs_p5 --json-only
python scripts/deploy.py --obs capers_egs_p6 --json-only
python scripts/deploy.py --obs capers_egs_p7 --json-only
python scripts/deploy.py --obs cosmos_ddt --json-only
python scripts/deploy.py --obs ember_cosmos_p12 --json-only
python scripts/deploy.py --obs ember_cosmos_p13 --json-only
python scripts/deploy.py --obs ember_cosmos_p14 --json-only
python scripts/deploy.py --obs ember_cosmos_p3 --json-only
python scripts/deploy.py --obs ember_cosmos_p4 --json-only
python scripts/deploy.py --obs ember_cosmos_p5 --json-only
python scripts/deploy.py --obs ember_uds_p1 --json-only
python scripts/deploy.py --obs ember_uds_p4 --json-only
python scripts/deploy.py --obs mom_cosmos_p1 --json-only
python scripts/deploy.py --obs mom_cosmos_p2 --json-only
python scripts/deploy.py --obs mom_cosmos_p3 --json-only
python scripts/deploy.py --obs mom_uds_p1 --json-only
python scripts/deploy.py --obs mom_uds_p2 --json-only
python scripts/deploy.py --obs rubies_egs_p51 --json-only
python scripts/deploy.py --obs rubies_egs_p52 --json-only
python scripts/deploy.py --obs rubies_egs_p53 --json-only
python scripts/deploy.py --obs rubies_egs_p61 --json-only
python scripts/deploy.py --obs rubies_egs_p62 --json-only
python scripts/deploy.py --obs rubies_egs_p63 --json-only
python scripts/deploy.py --obs rubies_uds_p11 --json-only
python scripts/deploy.py --obs rubies_uds_p12 --json-only
python scripts/deploy.py --obs rubies_uds_p13 --json-only
python scripts/deploy.py --obs rubies_uds_p21 --json-only
python scripts/deploy.py --obs rubies_uds_p22 --json-only
python scripts/deploy.py --obs rubies_uds_p23 --json-only
python scripts/deploy.py --obs rubies_uds_p31 --json-only
python scripts/deploy.py --obs rubies_uds_p32 --json-only
python scripts/deploy.py --obs rubies_uds_p33 --json-only
python scripts/deploy.py --obs rubies_uds_p41 --json-only
python scripts/deploy.py --obs rubies_uds_p42 --json-only
python scripts/deploy.py --obs rubies_uds_p43 --json-only
python scripts/deploy.py --obs zenith_p9 --json-only
python scripts/deploy.py --obs zenith_p16 --json-only
python scripts/deploy.py --obs zenith_p17 --json-only