#!/bin/zsh

python scripts/deploy.py --obs capers_cosmos_p1 --thumbnail-only 
python scripts/deploy.py --obs capers_cosmos_p2 --thumbnail-only 
python scripts/deploy.py --obs capers_cosmos_p3 --thumbnail-only 
python scripts/deploy.py --obs capers_cosmos_p4 --thumbnail-only 
python scripts/deploy.py --obs capers_cosmos_p5 --thumbnail-only 
python scripts/deploy.py --obs capers_cosmos_p6 --thumbnail-only 
python scripts/deploy.py --obs capers_cosmos_p7 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p1 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p2 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p3 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p4 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p5 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p6 --thumbnail-only 
python scripts/deploy.py --obs capers_uds_p7 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p1 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p2 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p3 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p4 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p5 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p6 --thumbnail-only 
python scripts/deploy.py --obs capers_egs_p7 --thumbnail-only 
python scripts/deploy.py --obs cosmos_ddt --thumbnail-only 
python scripts/deploy.py --obs ember_cosmos_p12 --thumbnail-only 
python scripts/deploy.py --obs ember_cosmos_p13 --thumbnail-only 
python scripts/deploy.py --obs ember_cosmos_p14 --thumbnail-only 
python scripts/deploy.py --obs ember_cosmos_p3 --thumbnail-only 
python scripts/deploy.py --obs ember_cosmos_p4 --thumbnail-only 
python scripts/deploy.py --obs ember_cosmos_p5 --thumbnail-only 
python scripts/deploy.py --obs ember_uds_p1 --thumbnail-only 
python scripts/deploy.py --obs ember_uds_p3 --thumbnail-only 
python scripts/deploy.py --obs ember_uds_p4 --thumbnail-only 
python scripts/deploy.py --obs mom_cosmos_p1 --thumbnail-only 
python scripts/deploy.py --obs mom_cosmos_p2 --thumbnail-only 
python scripts/deploy.py --obs mom_cosmos_p3 --thumbnail-only 
python scripts/deploy.py --obs mom_uds_p1 --thumbnail-only 
python scripts/deploy.py --obs mom_uds_p2 --thumbnail-only 
python scripts/deploy.py --obs rubies_egs_p51 --thumbnail-only 
python scripts/deploy.py --obs rubies_egs_p52 --thumbnail-only 
python scripts/deploy.py --obs rubies_egs_p53 --thumbnail-only 
python scripts/deploy.py --obs rubies_egs_p61 --thumbnail-only 
python scripts/deploy.py --obs rubies_egs_p62 --thumbnail-only 
python scripts/deploy.py --obs rubies_egs_p63 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p11 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p12 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p13 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p21 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p22 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p23 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p31 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p32 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p33 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p41 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p42 --thumbnail-only 
python scripts/deploy.py --obs rubies_uds_p43 --thumbnail-only 
python scripts/deploy.py --obs zenith_p9 --thumbnail-only 
python scripts/deploy.py --obs zenith_p16 --thumbnail-only 
python scripts/deploy.py --obs zenith_p17 --thumbnail-only 