[pipeline]
    version = "v0.2"

[environment]
    CRDS_SERVER_URL = "https://jwst-crds.stsci.edu"
    CRDS_PATH = "/Users/hba423/simmons/crds/"
    CRDS_CONTEXT = "jwst_1464.pmap"

[paths]
    data_dir = "/Users/hba423/simmons/campfire/pipeline/data" # Raw data (uncals) from MAST 
    products_dir = "/Users/hba423/simmons/campfire/pipeline/products" # Reduced data products (split by observation)
    pictureframe_dir = "/Users/hba423/simmons/campfire/pipeline/templates/pictureframe"
    continuum_templates_file = "/Users/hba423/simmons/campfire/pipeline/templates/continuum_templates.pickle"

[paths.r_curve_files]
    prism = "/Users/hba423/simmons/campfire/pipeline/templates/jwst_nirspec_prism_disp.fits"
    g395m = "/Users/hba423/simmons/campfire/pipeline/templates/jwst_nirspec_g395m_disp.fits"

[logging]
    level = "INFO"  # DEBUG, INFO, WARNING, ERROR
    format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[stage1]
    do_clean_flicker_noise = true
    mask_science_regions = true
    cleanup_uncal = true
    cleanup_rateints = true
    subtract_background = true
    box_size = 8
    sigma_clip = true
    bkg_estimator = 'median'
    plot = true

[stage2]
    set_stellarity = 1.0
    rectify = false # product rectified, background-subtracted products 

[stage3]
    cleanup_crfs = true

[fitting]
    ncores = 12
    overwrite = true
    save_models = false
