[capers_cosmos_p1]
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368001001*'
    gratings = ['PRISM']
    combine_dither = true # combine spectra from both dithers?

[capers_cosmos_p2]
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368004001*'
    gratings = ['PRISM']

[capers_cosmos_p3]
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368007001*'
    gratings = ['PRISM']

[capers_cosmos_p4]
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368010001*'
    gratings = ['PRISM']

[capers_cosmos_p5] # Note--didn't finish, rescheduled as obs67
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368013001*'
    gratings = ['PRISM']

[capers_cosmos_p6]
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368016001*'
    gratings = ['PRISM']

[capers_cosmos_p7]
    field = 'cosmos'
    data_subdir='6368'
    files = 'jw06368019001*'
    gratings = ['PRISM']

# [capers_uds_p2]
#     field = 'uds'
#     data_subdir='6368'
#     files = ['jw06368025001_*', 'jw06368026001_*', 'jw06368027001_*']
#     gratings = ['PRISM']

# [capers_uds_p3]
#     field = 'uds'
#     data_subdir='6368'
#     files = ['jw06368028001_*', 'jw06368029001_*', 'jw06368030001_*']
#     gratings = ['PRISM']

# [capers_uds_p4]
#     field = 'uds'
#     data_subdir='6368'
#     files = 'jw06368031*'
#     gratings = ['PRISM']

# [capers_uds_p6]
#     field = 'uds'
#     data_subdir='6368'
#     files = 'jw06368040*'
#     gratings = ['PRISM']

[capers_egs_p1]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368044001*'
    gratings = ['PRISM']

[capers_egs_p2]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368047001*'
    gratings = ['PRISM']

[capers_egs_p3]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368049001*'
    gratings = ['PRISM']

[capers_egs_p4]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368053001*'
    gratings = ['PRISM']

[capers_egs_p5]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368055001*'
    gratings = ['PRISM']

[capers_egs_p6]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368065001*'
    gratings = ['PRISM']

[capers_egs_p7]
    field = 'egs'
    data_subdir='6368'
    files = 'jw06368061001*'
    gratings = ['PRISM']

[rubies_uds_p11]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233001001*'
    gratings = ['PRISM', 'G395M']
    
[rubies_uds_p12]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233001002*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p13]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233001003*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p21]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233002001*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p22]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233002002*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p23]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233002003*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p31]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233003001*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p32]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233003002*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p33]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233003003*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p41]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233004001*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p42]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233004002*'
    gratings = ['PRISM', 'G395M']

[rubies_uds_p43]
    field = 'uds'
    data_subdir='4233'
    files = 'jw04233004003*'
    gratings = ['PRISM', 'G395M']

[rubies_egs_p51]
    field = 'egs'
    data_subdir='4233'
    files = 'jw04233005001*'
    gratings = ['PRISM', 'G395M']

[rubies_egs_p52]
    field = 'egs'
    data_subdir='4233'
    files = 'jw04233005002*'
    gratings = ['PRISM', 'G395M']

[rubies_egs_p53]
    field = 'egs'
    data_subdir='4233'
    files = 'jw04233005003*'
    gratings = ['PRISM', 'G395M']

[rubies_egs_p61]
    field = 'egs'
    data_subdir='4233'
    files = 'jw04233006001*'
    gratings = ['PRISM', 'G395M']

[rubies_egs_p62]
    field = 'egs'
    data_subdir='4233'
    files = 'jw04233006002*'
    gratings = ['PRISM', 'G395M']

[rubies_egs_p63]
    field = 'egs'
    data_subdir='4233'
    files = 'jw04233006003*'
    gratings = ['PRISM', 'G395M']





[ember_uds_p1]
    field = 'uds'
    data_subdir='7076'
    files = 'jw07076016001*'
    gratings = ['PRISM', 'G395M']

[ember_uds_p4]
    field = 'uds'
    data_subdir='7076'
    files = 'jw07076019001*'
    gratings = ['PRISM', 'G395M']

[ember_gds_p1]
    field = 'gds'
    data_subdir='7076'
    files = 'jw07076023001*'
    gratings = ['PRISM']

[ember_cosmos_p1]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076001001*'
    gratings = ['PRISM', 'G395M']

[ember_cosmos_p3]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076003001*'
    gratings = ['PRISM', 'G395M']

[ember_cosmos_p4]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076004001*'
    gratings = ['PRISM', 'G395M']

[ember_cosmos_p5]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076005001*'
    gratings = ['PRISM', 'G395M']

[ember_cosmos_p12]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076012001*'
    gratings = ['PRISM', 'G395M']

[ember_cosmos_p14]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076014001*'
    gratings = ['PRISM', 'G395M']

[ember_cosmos_p13]
    field = 'cosmos'
    data_subdir = '7076'
    files = 'jw07076013001*'
    gratings = ['PRISM', 'G395M']




[cosmos_ddt]
    field = 'cosmos'
    data_subdir='6585'
    files = 'jw06585004001*'
    gratings = ['PRISM']


[mom_uds_p1]
    field = 'uds'
    data_subdir = '5224'
    files = 'jw05224001001*'
    gratings = ['PRISM']

[mom_uds_p2]
    field = 'uds'
    data_subdir = '5224'
    files = 'jw05224002001*'
    gratings = ['PRISM']

[mom_cosmos_p1]
    field = 'cosmos'
    data_subdir = '5224'
    files = 'jw05224003001*'
    gratings = ['PRISM']

[mom_cosmos_p2]
    field = 'cosmos'
    data_subdir = '5224'
    files = 'jw05224004001*'
    gratings = ['PRISM']

[mom_cosmos_p3]
    field = 'cosmos'
    data_subdir = '5224'
    files = 'jw05224005001*'
    gratings = ['PRISM']

[ceers_ddt]
    field = 'egs'
    data_subdir = '2750'
    files = 'jw02750002001*'
    gratings = ['PRISM']

[zenith_p9]
    field = 'cosmos'
    data_subdir = '7417'
    files = 'jw07417009001*'
    gratings = ['PRISM']

[zenith_p16]
    field = 'cosmos'
    data_subdir = '7417'
    files = 'jw07417016001*'
    gratings = ['PRISM']

[zenith_p17]
    field = 'cosmos'
    data_subdir = '7417'
    files = 'jw07417017001*'
    gratings = ['PRISM']