"""The inspected-redshift reference file: ``reference/nirspec/<obs>/redshifts.toml``.

The cloud→local half of the emission-line loop. Inspection happens on the
portal (``objects.redshift`` / ``objects.redshift_quality``, one tuple per
sky position); ``campfire pull --obs X`` (or ``campfire deploy nirspec
pull-redshifts``) materializes those decisions into this file, keyed by
**target_id** (``<obs>_<source_id>``, the summary ECSV's ``object_id``), and
``cfpipe nirspec linefit`` reads it. The pipeline never talks to the portal:
this file is the whole contract, and it is regenerated verbatim from the DB
on every pull — edit redshifts on the web, not here.

Format::

    # inspected redshifts for ember_uds_p4
    # Generated by campfire pull at 2026-09-09T12:00:00Z ...

    [meta]
    observation = "ember_uds_p4"
    generated_at = "2026-09-09T12:00:00Z"

    [targets.ember_uds_p4_1234]
    object_id = "CAMPFIRE-J021739.21-051204.7"
    redshift = 5.1234
    quality = 4            # 0 uninspected, 1 impossible, 2 tentative, 3 probable, 4 secure
    version = 7            # objects.version at pull time (staleness ledger)
    inspected_at = "2026-08-30T21:14:03+00:00"

``redshift`` is the portal's generated column (NULL when quality is 1, so an
"impossible" object is written with ``quality = 1`` and no ``redshift`` key).
Both the writer (used by the pull) and the reader (used by the fitter) live
here so the two sides cannot drift.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

import toml

REDSHIFTS_FILENAME = 'redshifts.toml'

QUALITY_LABELS = {0: 'uninspected', 1: 'impossible', 2: 'tentative', 3: 'probable', 4: 'secure'}


@dataclass(frozen=True)
class RedshiftEntry:
    target_id: str
    redshift: Optional[float]
    quality: int
    object_id: Optional[str] = None
    version: Optional[int] = None
    inspected_at: Optional[str] = None

    @property
    def usable(self) -> bool:
        return self.redshift is not None and self.quality >= 2


def redshifts_path(reference_dir: str) -> str:
    return os.path.join(reference_dir, REDSHIFTS_FILENAME)


def serialize_redshifts(entries, obs_name: str, generated_at: str | None = None,
                        generated_by: str = 'campfire pull') -> str:
    """Render entries as the TOML text (deterministic order: by target_id)."""
    generated_at = generated_at or datetime.now(timezone.utc).isoformat()
    lines = [
        f'# inspected redshifts for {obs_name}',
        '# One table per target (the summary ECSV object_id = <obs>_<source_id>).',
        '# quality: 0 uninspected, 1 impossible, 2 tentative (~50%), 3 probable (~80%), 4 secure (>95%)',
        '# redshift is absent when quality = 1 (impossible).',
        f'# Generated by {generated_by} at {generated_at}',
        '# — regenerated from the portal (objects.redshift / redshift_quality) on each pull;',
        '#   edit redshifts on the web, not here. cfpipe nirspec linefit reads this file.',
        '',
        '[meta]',
        f'observation = {_q(obs_name)}',
        f'generated_at = {_q(generated_at)}',
        '',
    ]
    for e in sorted(entries, key=lambda e: e.target_id):
        lines.append(f'[targets.{_key(e.target_id)}]')
        if e.object_id is not None:
            lines.append(f'object_id = {_q(e.object_id)}')
        if e.redshift is not None:
            lines.append(f'redshift = {float(e.redshift):.6f}')
        lines.append(f'quality = {int(e.quality)}')
        if e.version is not None:
            lines.append(f'version = {int(e.version)}')
        if e.inspected_at:
            lines.append(f'inspected_at = {_q(e.inspected_at)}')
        lines.append('')
    return '\n'.join(lines) + '\n'


def write_redshifts(entries, filepath: str, obs_name: str, **kw) -> None:
    """Atomic write (tmp + rename)."""
    text = serialize_redshifts(entries, obs_name, **kw)
    os.makedirs(os.path.dirname(filepath) or '.', exist_ok=True)
    tmp = filepath + '.tmp'
    with open(tmp, 'w') as f:
        f.write(text)
    os.replace(tmp, filepath)


def load_redshifts(filepath: str) -> dict[str, RedshiftEntry]:
    """Parse the file into ``{target_id: RedshiftEntry}`` (empty if absent)."""
    if not os.path.exists(filepath):
        return {}
    data = toml.load(filepath)
    out = {}
    for target_id, sec in (data.get('targets') or {}).items():
        z = sec.get('redshift')
        out[target_id] = RedshiftEntry(
            target_id=str(target_id),
            redshift=float(z) if z is not None else None,
            quality=int(sec.get('quality', 0)),
            object_id=sec.get('object_id'),
            version=int(sec['version']) if sec.get('version') is not None else None,
            inspected_at=sec.get('inspected_at'),
        )
    return out


def _q(s) -> str:
    return toml.dumps({'k': str(s)}).split('=', 1)[1].strip()


def _key(target_id: str) -> str:
    """TOML table key: bare when it is a valid bare key, quoted otherwise."""
    if target_id and all(c.isalnum() or c in '-_' for c in target_id):
        return target_id
    return _q(target_id)
