#!/usr/bin/env python
"""Build ``wisp_manifest.toml`` from a local directory of wisp templates.

The manifest is the committed source of truth the pipeline ships and validates
against (see ``campfire_pipeline/nircam/wisp_cache.py`` and
``pipeline/WISP_TEMPLATE_HOSTING.md``). This tool scans a local template
directory, computes the sha256 + byte size of every ``WISP_*.fits`` file, checks
that each ``(detector, filter)`` has the complete 4-variant set, and writes the
manifest with the given public ``base_url`` baked in.

Publish loop:
    1. Upload the exact files in <template_dir> to the public host, under a
       versioned path (e.g. .../wisps/2026.1/).
    2. Run this script pointing at the SAME local files:
         python scripts/build_wisp_manifest.py ./local_wisps \
             --base-url https://wisps.example.org/wisps/2026.1 --version 2026.1
    3. Commit the regenerated
       campfire_pipeline/data/wisp_manifest.toml.
"""

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path

# The detectors that carry wisps and the four smoothing variants each must have.
# Kept in lockstep with WISP_DETECTORS / template naming in
# campfire_pipeline/nircam/wisp_cache.py.
WISP_DETECTORS = {"NRCA3", "NRCA4", "NRCB3", "NRCB4"}
VARIANT_SUFFIXES = (
    "masked",
    "masked_smoothed_1x1",
    "masked_smoothed_2x2",
    "masked_smoothed_3x3",
)

_NAME_RE = re.compile(
    r"^WISP_(?P<det>NRC[AB][0-9])_(?P<filt>[A-Z0-9]+)_CLEAR_(?P<variant>.+)\.fits$"
)

_DEFAULT_OUT = (
    Path(__file__).resolve().parent.parent
    / "campfire_pipeline" / "data" / "wisp_manifest.toml"
)


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("template_dir", type=Path,
                    help="Directory of WISP_*.fits files to publish.")
    ap.add_argument("--base-url", required=True,
                    help="Public HTTPS prefix files are served from "
                         "(e.g. https://wisps.example.org/wisps/2026.1).")
    ap.add_argument("--version", required=True,
                    help='Version tag, mirrors the base-url path (e.g. "2026.1").')
    ap.add_argument("--out", type=Path, default=_DEFAULT_OUT,
                    help=f"Manifest output path (default: {_DEFAULT_OUT}).")
    args = ap.parse_args(argv)

    if not args.template_dir.is_dir():
        ap.error(f"template_dir does not exist: {args.template_dir}")

    files = sorted(p for p in args.template_dir.iterdir()
                   if p.name.startswith("WISP_") and p.suffix == ".fits")
    if not files:
        ap.error(f"no WISP_*.fits files found in {args.template_dir}")

    # Group by (detector, filter) so we can enforce the complete 4-variant set.
    groups = {}
    entries = []
    for p in files:
        m = _NAME_RE.match(p.name)
        if not m:
            print(f"  WARN: unrecognized filename, skipping: {p.name}", file=sys.stderr)
            continue
        det = m.group("det")
        if det not in WISP_DETECTORS:
            print(f"  WARN: {p.name} has non-wisp detector {det}, skipping",
                  file=sys.stderr)
            continue
        groups.setdefault((det, m.group("filt")), set()).add(m.group("variant"))
        print(f"  hashing {p.name} …", file=sys.stderr)
        entries.append((p.name, _sha256(p), p.stat().st_size))

    # Completeness check — the pipeline hard-fails on a partial set, so catch it
    # here at publish time instead.
    incomplete = False
    for (det, filt), variants in sorted(groups.items()):
        missing = set(VARIANT_SUFFIXES) - variants
        if missing:
            incomplete = True
            print(f"  ERROR: {det}/{filt} missing variants: "
                  f"{', '.join(sorted(missing))}", file=sys.stderr)
    if incomplete:
        ap.error("one or more (detector, filter) sets are incomplete; "
                 "fix the template directory and re-run.")

    lines = [
        "# NIRCam wisp template manifest — GENERATED by "
        "scripts/build_wisp_manifest.py.",
        "# Do not hand-edit. See the script and pipeline/WISP_TEMPLATE_HOSTING.md.",
        "",
        f'base_url = "{args.base_url.rstrip("/")}"',
        f'version = "{args.version}"',
        "",
    ]
    for name, sha, nbytes in sorted(entries):
        lines += [
            "[[template]]",
            f'name   = "{name}"',
            f'sha256 = "{sha}"',
            f"bytes  = {nbytes}",
            "",
        ]

    args.out.write_text("\n".join(lines))
    print(f"\nWrote {args.out} — {len(entries)} templates across "
          f"{len(groups)} (detector, filter) groups.", file=sys.stderr)


if __name__ == "__main__":
    main()
