#!/usr/bin/env python3
"""Mirror the pipeline's emission-line catalog into web/lib/linelist.json.

The web portal's line filter and object-page line table need the catalog
that ``cfpipe nirspec linefit`` measures — names, labels, rest wavelengths,
and which lines are the components of a doublet total — and the web builds
from ``web/`` alone, so the JSON is committed and this script keeps it in
step with ``pipeline/campfire_pipeline/nirspec/linelist.py`` (the source of
truth). The module is loaded by file path, not imported through the
package, so the check runs on a bare python3 (CI: web-linelist.yml).

    python scripts/sync_linelist.py          # rewrite web/lib/linelist.json
    python scripts/sync_linelist.py --check  # exit 1 if it is out of date
"""
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'pipeline' / 'campfire_pipeline' / 'nirspec' / 'linelist.py'
DST = ROOT / 'web' / 'lib' / 'linelist.json'


def load_linelist():
    spec = importlib.util.spec_from_file_location('campfire_linelist', SRC)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod      # dataclasses resolve annotations via sys.modules
    spec.loader.exec_module(mod)
    return mod


def build(mod) -> dict:
    member_of = {m: d.name for d in mod.DOUBLETS for m in d.members}
    entries = []
    for line in mod.LINES:
        entries.append({
            'name': line.name,
            'label': line.label,
            'wave': line.wave,
            'kind': 'line',
            'tied_to': line.tie[0] if line.tie else None,
            'broad': bool(line.broad),
            'doublet': member_of.get(line.name),
        })
    for d in mod.DOUBLETS:
        entries.append({
            'name': d.name,
            'label': d.label,
            'wave': round(d.wave, 3),
            'kind': 'doublet',
            'tied_to': None,
            'broad': False,
            'members': list(d.members),
        })
    entries.sort(key=lambda e: (e['wave'], e['name']))
    return {
        '_comment': 'GENERATED by scripts/sync_linelist.py from pipeline/campfire_pipeline/nirspec/linelist.py; do not edit.',
        'lines': entries,
    }


def render(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2) + '\n'


def main(argv) -> int:
    check = '--check' in argv
    text = render(build(load_linelist()))
    current = DST.read_text(encoding='utf-8') if DST.exists() else None
    if current == text:
        print(f'sync_linelist: {DST.relative_to(ROOT)} up to date')
        return 0
    if check:
        print(f'sync_linelist: {DST.relative_to(ROOT)} is {"missing" if current is None else "out of date"}; '
              'run `python scripts/sync_linelist.py` and commit the result', file=sys.stderr)
        return 1
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(text, encoding='utf-8')
    print(f'sync_linelist: wrote {DST.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
