"""Unit tests for the P3b NIRSpec rate-mask pull (design §3.5).

The deploy side (`_serialize_regfile` reuse + the `.reg` filename derivation) runs
here; the cross-package hash-stability bridge to the pipeline is guarded by
importorskip so it runs in CI (where campfire_pipeline is installed) and is skipped
in the deploy-only dev container. The full DB SELECT → file write runs live against
local Supabase in CI.
"""
import pytest

from campfire.deploy.nircam_masks import _serialize_regfile


TRIANGLE = [{"vertices": [[1.0, 1.0], [10.0, 1.0], [10.0, 10.0]]}]


def test_serialize_regfile_shape():
    out = _serialize_regfile(TRIANGLE, generated_at="2026-07-04T00:00:00Z")
    lines = out.splitlines()
    assert lines[0] == "# Region file format: DS9 version 4.1"
    assert any(l.startswith("# Generated by campfire deploy") for l in lines)
    assert "image" in lines
    # one polygon line, 4-decimal coords, no label
    poly = [l for l in lines if l.startswith("polygon(")]
    assert poly == ["polygon(1.0000,1.0000,10.0000,1.0000,10.0000,10.0000)"]


def test_serialize_regfile_drops_degenerate_polygons():
    polys = TRIANGLE + [{"vertices": [[1, 1], [2, 2]]}]  # 2-vertex → dropped
    out = _serialize_regfile(polys, generated_at="t")
    assert len([l for l in out.splitlines() if l.startswith("polygon(")]) == 1


def test_rate_reg_filename_derivation():
    # The pull writes filename.replace('_rate.fits', '.reg'); it must equal the
    # <exposure_root>_<detector>.reg stem the pipeline's _rate_basename produces.
    filename = "jw07076020001_04101_00001_nrs1_rate.fits"
    exposure_root, detector = "jw07076020001_04101_00001", "nrs1"
    reg_name = filename.replace("_rate.fits", ".reg")
    assert reg_name == "jw07076020001_04101_00001_nrs1.reg"
    assert reg_name == f"{exposure_root}_{detector}.reg"


def test_serialize_hash_stable_across_timestamps():
    # Cross-package guard (CI): the generated-at timestamp lives in a '#' line that
    # masks.canonicalize strips, so re-pulls are idempotent (same polygons → same
    # CFMASKSH) while an actual polygon edit flips the hash and triggers re-apply.
    masks = pytest.importorskip("campfire_pipeline.nirspec.masks")
    a = _serialize_regfile(TRIANGLE, generated_at="2026-01-01T00:00:00Z")
    b = _serialize_regfile(TRIANGLE, generated_at="2026-07-04T12:00:00Z")
    assert masks.hash_mask(a) == masks.hash_mask(b) != ""
    c = _serialize_regfile(
        [{"vertices": [[2, 2], [20, 2], [20, 20]]}], generated_at="t")
    assert masks.hash_mask(c) != masks.hash_mask(a)
