"""Unit tests for the P7 NIRSpec flag pull-back (design §4.3/§7).

The pure serialization + authority-merge logic runs here (no DB). The cross-package
provenance round-trip through the pipeline writer/reader is guarded by importorskip so
it runs in CI (where campfire_pipeline is installed) and skips in the deploy-only dev
container. The full DB SELECT → file write runs live against local Supabase in CI.
"""
import toml

from campfire.deploy.nirspec_flags import (
    merge_pulled_stuck_shutters,
    _serialize_bkg_overrides,
)


# ---------------------------------------------------------------------------
# bkg-override serialization
# ---------------------------------------------------------------------------

def test_serialize_bkg_overrides_shape_and_roundtrip():
    data = {"jw06368001001_03101": {"12345": {"3": [1]}}}
    out = _serialize_bkg_overrides(data, "ember_uds_p4", generated_at="t")
    assert "[jw06368001001_03101]" in out
    assert "12345 = {3 = [1]}" in out
    assert any(l.startswith("# Generated by campfire deploy") for l in out.splitlines())
    # toml.load reads it back into the exact shape observation.bkg_overrides expects
    parsed = toml.loads(out)
    assert parsed["jw06368001001_03101"]["12345"]["3"] == [1]


def test_serialize_bkg_overrides_empty_list_is_preserved():
    # An empty bkg list for a nod means "exclude this nod" (CFP_BKG='excluded:override')
    # and must NOT be dropped — distinct from an absent key.
    data = {"root_a": {"999": {"3": []}}}
    out = _serialize_bkg_overrides(data, "obs", generated_at="t")
    assert "999 = {3 = []}" in out
    assert toml.loads(out)["root_a"]["999"]["3"] == []


def test_serialize_bkg_overrides_multi_nod_sorted():
    data = {"r": {"1": {"10": [2], "2": [1, 3]}}}
    out = _serialize_bkg_overrides(data, "obs", generated_at="t")
    # nod keys sorted numerically (2 before 10), bkg-nod values verbatim
    assert "1 = {2 = [1, 3], 10 = [2]}" in out
    assert toml.loads(out)["r"]["1"] == {"2": [1, 3], "10": [2]}


# ---------------------------------------------------------------------------
# stuck-shutter authority merge (hand > web > auto)
# ---------------------------------------------------------------------------

def test_merge_hand_protects_web():
    existing = {("r", "1"): ([5], "hand")}
    db_web = {("r", "1"): [2, 3]}
    data, prov, stats = merge_pulled_stuck_shutters(existing, db_web)
    # hand entry survives untouched; web overlay blocked
    assert data["r"]["1"] == [5]
    assert prov[("r", "1")] == "hand"
    assert stats["hand_protected"] == 1
    assert stats["web"] == 0


def test_merge_web_overlays_auto():
    existing = {("r", "1"): ([9], "auto")}
    db_web = {("r", "1"): [2]}
    data, prov, stats = merge_pulled_stuck_shutters(existing, db_web)
    assert data["r"]["1"] == [2]
    assert prov[("r", "1")] == "web"
    assert stats["web"] == 1


def test_merge_web_dropped_when_absent_from_db():
    # A prior web entry the DB no longer flags is dropped (reversibility).
    existing = {("r", "1"): ([2], "web")}
    db_web = {}
    data, prov, stats = merge_pulled_stuck_shutters(existing, db_web)
    assert "r" not in data
    assert stats["web_dropped"] == 1


def test_merge_hand_and_auto_retained_when_absent_from_db():
    existing = {("r", "1"): ([5], "hand"), ("r", "2"): ([7], "auto")}
    db_web = {}
    data, prov, stats = merge_pulled_stuck_shutters(existing, db_web)
    assert data["r"]["1"] == [5] and prov[("r", "1")] == "hand"
    assert data["r"]["2"] == [7] and prov[("r", "2")] == "auto"


def test_merge_untagged_legacy_treated_as_hand():
    # load_stuck_shutters_tagged classifies untagged entries as hand (never dropped).
    existing = {("r", "1"): ([4], "hand")}  # what the loader returns for an untagged line
    db_web = {("r", "1"): [1]}
    data, prov, stats = merge_pulled_stuck_shutters(existing, db_web)
    assert data["r"]["1"] == [4]  # hand wins
    assert stats["hand_protected"] == 1


def test_merge_fresh_web_entry_added():
    data, prov, stats = merge_pulled_stuck_shutters({}, {("r", "3"): [1, 2]})
    assert data["r"]["3"] == [1, 2]
    assert prov[("r", "3")] == "web"
    assert stats["web"] == 1


# ---------------------------------------------------------------------------
# Cross-package provenance round-trip (needs the pipeline writer/reader)
# ---------------------------------------------------------------------------

def test_provenance_roundtrip_through_pipeline(tmp_path):
    ss = __import__("pytest").importorskip("campfire_pipeline.nirspec.stuck_shutters")

    path = str(tmp_path / "stuck_closed_shutters.toml")
    data = {"r": {"1": [5], "2": [3], "3": [1]}}
    provenance = {("r", "1"): "hand", ("r", "2"): "web", ("r", "3"): "auto"}
    ss.write_stuck_shutters_toml(data, path, "obs", provenance=provenance)

    # tags survive a raw re-read
    tagged = ss.load_stuck_shutters_tagged(path)
    assert tagged[("r", "1")] == ([5], "hand")
    assert tagged[("r", "2")] == ([3], "web")
    assert tagged[("r", "3")] == ([1], "auto")

    # ...and a subsequent auto-detect rewrite preserves the hand/web tags while
    # tagging a freshly-detected entry `auto` (the anti-collapse guarantee).
    existing_plain = {r: {s: sh for s, (sh, _t) in
                          {k[1]: v for k, v in tagged.items() if k[0] == r}.items()}
                      for r in {k[0] for k in tagged}}
    detected = {"r": {4: [2]}}
    merged, updated = ss.merge_stuck_shutters(existing_plain, detected)
    prov2 = {k: t for k, (_sh, t) in tagged.items()}
    for (root, sid) in updated:
        prov2[(root, str(sid))] = "auto"
    ss.write_stuck_shutters_toml(merged, path, "obs", provenance=prov2)

    tagged2 = ss.load_stuck_shutters_tagged(path)
    assert tagged2[("r", "1")][1] == "hand"
    assert tagged2[("r", "2")][1] == "web"
    assert tagged2[("r", "4")] == ([2], "auto")
