"""Unit tests for the NIRCam mask drift report (epic #261, N6, D8).

Pure-Python: a fake Supabase client + on-disk .reg fixtures under tmp_path.
"""
import types

from campfire.deploy import nircam_masks as nm


class _FakeQuery:
    def __init__(self, rows):
        self._rows = rows
        self._eq = []

    def select(self, *a, **k):
        return self

    def eq(self, col, val):
        self._eq.append((col, val))
        return self

    def execute(self):
        rows = list(self._rows)
        for col, val in self._eq:
            rows = [r for r in rows if r.get(col) == val]
        return types.SimpleNamespace(data=rows)


class _FakeClient:
    def __init__(self, rows):
        self._rows = rows

    def table(self, name):
        return _FakeQuery(self._rows)


_GENERATED_HEADER = (
    '# Region file format: DS9 version 4.1\n'
    '# Generated by campfire deploy pull-masks at 2026-01-01T00:00:00+00:00.\n'
    '# Manual edits will be overwritten on the next pull.\n'
    'image\n'
)
_POLY = 'polygon(1,1,2,2,3,3)\n'


def test_mask_drift_three_categories(monkeypatch, tmp_path):
    masks = tmp_path / 'masks'
    (masks / 'f444w').mkdir(parents=True)
    # (1) generated .reg whose DB row now has no polygons -> STALE
    (masks / 'f444w' / 'cleared.reg').write_text(_GENERATED_HEADER + _POLY)
    # (2) non-generated .reg with no DB mask -> LOCAL_ONLY
    (masks / 'f444w' / 'handdrawn.reg').write_text('image\n' + _POLY)
    # (3) _imported/ archive must be ignored entirely
    (masks / 'f444w' / '_imported').mkdir()
    (masks / 'f444w' / '_imported' / 'old.reg').write_text(_GENERATED_HEADER)

    rows = [
        {'field': 'cosmos', 'filter': 'f444w', 'filename': 'cleared', 'mask_regions': {'polygons': []}},
        {'field': 'cosmos', 'filter': 'f444w', 'filename': 'onlydb',
         'mask_regions': {'polygons': [{'vertices': [[1, 1], [2, 2], [3, 3]]}]}},
        # 'handdrawn' has no row at all.
    ]
    monkeypatch.setattr('campfire.deploy.supabase.get_supabase_client',
                        lambda config: _FakeClient(rows))
    monkeypatch.setattr('campfire.deploy.nircam._resolve_nircam_dirs',
                        lambda field: {'masks': masks})

    report = nm.mask_drift_report('cosmos', config={})

    assert any('cleared.reg' in p for p in report['stale'])
    assert any('handdrawn.reg' in p for p in report['local_only'])
    assert 'f444w/onlydb' in report['not_materialized']
    # _imported/ never walked
    everything = report['stale'] + report['local_only']
    assert not any('old.reg' in p for p in everything)


def test_mask_drift_clean(monkeypatch, tmp_path):
    masks = tmp_path / 'masks'
    (masks / 'f444w').mkdir(parents=True)
    (masks / 'f444w' / 'ok.reg').write_text(_GENERATED_HEADER + _POLY)
    rows = [{'field': 'cosmos', 'filter': 'f444w', 'filename': 'ok',
             'mask_regions': {'polygons': [{'vertices': [[1, 1], [2, 2], [3, 3]]}]}}]
    monkeypatch.setattr('campfire.deploy.supabase.get_supabase_client',
                        lambda config: _FakeClient(rows))
    monkeypatch.setattr('campfire.deploy.nircam._resolve_nircam_dirs',
                        lambda field: {'masks': masks})
    report = nm.mask_drift_report('cosmos', config={})
    assert report == {'stale': [], 'local_only': [], 'not_materialized': []}
