-- Fix tag creation for non-admins (issue #469).
--
-- Since the tag-sharing rework (20260731200000_tag_sharing.sql), select_lists
-- gates visibility through viewable_list_ids(). SELECT policies are also
-- enforced on rows returned by INSERT ... RETURNING, and viewable_list_ids()
-- is STABLE, so it runs under the statement's snapshot and cannot see the row
-- being inserted -- the web portal's insert().select() therefore failed with
-- "new row violates row-level security policy" for every non-admin. Add a
-- direct created_by disjunct, evaluated against the candidate row itself, so
-- owned rows pass without the table lookup. No visibility change: owned lists
-- were already in viewable_list_ids(), and link accounts stay excluded.
--
-- Hand-authored rather than generated by `supabase db diff` (matches the
-- declarative source in supabase/schemas/policies.sql).

DROP POLICY IF EXISTS "select_lists" ON object_lists;
CREATE POLICY "select_lists"
  ON object_lists FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    AND (
      created_by = (SELECT auth.uid())
      OR id IN (SELECT public.viewable_list_ids())
    )
  );
