-- Share links: admin-minted URLs scoped to one NIRCam field or one NIRSpec
-- observation, for viewers with no CAMPFIRE account.
-- See docs/design-public-mirror.md. Declarative source: supabase/schemas/.
--
-- Hand-authored rather than generated by `supabase db diff`. Verified by
-- building one database from supabase/migrations/ and another from
-- supabase/schemas/, applying this file to the former, and diffing the two
-- pg_dump outputs to empty -- the same reconciliation the diff engine performs.

-- ---------------------------------------------------------------------------
-- user_profiles.is_link_account
-- ---------------------------------------------------------------------------

ALTER TABLE public.user_profiles
    ADD COLUMN IF NOT EXISTS is_link_account boolean NOT NULL DEFAULT false;

-- A link account is read-only, structurally. can_comment DEFAULTS TO TRUE, so
-- without this a mint path that simply forgets the column yields a share link
-- whose holder can comment on the archive.
ALTER TABLE public.user_profiles
    DROP CONSTRAINT IF EXISTS user_profiles_link_account_readonly;
ALTER TABLE public.user_profiles
    ADD CONSTRAINT user_profiles_link_account_readonly CHECK (
        NOT (is_link_account AND (COALESCE(can_comment, false)
                                  OR COALESCE(can_inspect, false)
                                  OR COALESCE(is_admin, false)))
    );

-- ---------------------------------------------------------------------------
-- share_links
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.share_links (
    token text NOT NULL,
    label text NOT NULL,
    observation text,
    field text,
    link_user_id uuid NOT NULL,
    link_password text NOT NULL,
    include_drafts boolean NOT NULL DEFAULT false,
    allow_download boolean NOT NULL DEFAULT true,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    last_seen_at timestamp with time zone,
    view_count integer NOT NULL DEFAULT 0,
    CONSTRAINT share_links_scope_check CHECK ((num_nonnulls(observation, field) = 1))
);

ALTER TABLE public.share_links OWNER TO postgres;

COMMENT ON TABLE public.share_links IS 'Admin-minted share links scoped to one NIRCam field or NIRSpec observation. Each row is backed by a synthetic link account (link_user_id). See docs/design-public-mirror.md.';

ALTER TABLE ONLY public.share_links
    DROP CONSTRAINT IF EXISTS share_links_pkey;
ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_pkey PRIMARY KEY (token);

ALTER TABLE ONLY public.share_links
    DROP CONSTRAINT IF EXISTS share_links_link_user_id_key;
ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_link_user_id_key UNIQUE (link_user_id);

ALTER TABLE ONLY public.share_links
    DROP CONSTRAINT IF EXISTS share_links_link_user_id_fkey;
ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_link_user_id_fkey FOREIGN KEY (link_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.share_links
    DROP CONSTRAINT IF EXISTS share_links_created_by_fkey;
ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);

-- link_password is a live credential and admins browse through `authenticated`
-- like everyone else. RLS is row-level and cannot withhold a column, so the
-- column-level REVOKE is what keeps the credential server-side.
GRANT ALL ON TABLE public.share_links TO authenticated;
GRANT ALL ON TABLE public.share_links TO service_role;
REVOKE SELECT (link_password) ON TABLE public.share_links FROM authenticated;

CREATE INDEX IF NOT EXISTS idx_share_links_observation
    ON public.share_links USING btree (observation) WHERE (observation IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_share_links_field
    ON public.share_links USING btree (field) WHERE (field IS NOT NULL);

ALTER TABLE public.share_links ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Link-scope helpers + the narrowed accessible_program_slugs()
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_link_account()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT is_link_account FROM user_profiles WHERE user_id = auth.uid()),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_link_account() TO authenticated;


CREATE OR REPLACE FUNCTION public.link_observation()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT sl.observation
  FROM share_links sl
  WHERE sl.link_user_id = auth.uid()
    AND sl.revoked_at IS NULL
    AND (sl.expires_at IS NULL OR sl.expires_at > now());
$$;

GRANT EXECUTE ON FUNCTION public.link_observation() TO authenticated;


CREATE OR REPLACE FUNCTION public.link_field()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT sl.field
  FROM share_links sl
  WHERE sl.link_user_id = auth.uid()
    AND sl.revoked_at IS NULL
    AND (sl.expires_at IS NULL OR sl.expires_at > now());
$$;

GRANT EXECUTE ON FUNCTION public.link_field() TO authenticated;


CREATE OR REPLACE FUNCTION public.link_sees_drafts()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT sl.include_drafts
     FROM share_links sl
     WHERE sl.link_user_id = auth.uid()
       AND sl.revoked_at IS NULL
       AND (sl.expires_at IS NULL OR sl.expires_at > now())),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.link_sees_drafts() TO authenticated;


CREATE OR REPLACE FUNCTION public.link_allows_download()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT sl.allow_download
     FROM share_links sl
     WHERE sl.link_user_id = auth.uid()
       AND sl.revoked_at IS NULL
       AND (sl.expires_at IS NULL OR sl.expires_at > now())),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.link_allows_download() TO authenticated;


CREATE OR REPLACE FUNCTION public.accessible_program_slugs()
RETURNS text[]
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  -- Share links (docs/design-public-mirror.md §5.1): a link account gets ONLY
  -- the program of its scoped observation. No user_program_access union (it has
  -- no grants), no is_public union, no admin union.
  --
  -- Dropping is_public is the load-bearing part. Without it, handing someone a
  -- share link would hand them every public program in the archive -- and
  -- because ~20 policies route through this function, that one omission would
  -- leak through all of them at once. A field-scoped link gets '{}': NIRCam is
  -- not program-gated at all, so its narrowing lives on the field axis instead.
  SELECT CASE WHEN public.is_link_account() THEN
    COALESCE(
      (SELECT array_agg(DISTINCT o.program_slug)
       FROM observations o
       WHERE o.name = public.link_observation()),
      '{}'::text[]
    )
  ELSE
    COALESCE(
      (SELECT array_agg(DISTINCT slug)
       FROM (
         SELECT program_slug AS slug
         FROM user_program_access
         WHERE user_id = auth.uid()
         UNION
         SELECT slug
         FROM programs
         WHERE is_public = true
         UNION
         -- Admins (the operators) inherit access to every program. This is the
         -- single point where admin access is granted to all program-gated data:
         -- every RLS SELECT policy routes through accessible_program_slugs(), so
         -- this lets admins read back rows they deploy for private programs
         -- (otherwise an upsert's RETURNING fails the SELECT policy -> 42501).
         SELECT slug
         FROM programs
         WHERE public.is_admin()
       ) sub),
      '{}'::text[]
    )
  END;
$$;

GRANT EXECUTE ON FUNCTION public.accessible_program_slugs() TO authenticated;


-- ---------------------------------------------------------------------------
-- RLS narrowing (docs/design-public-mirror.md §5)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "authenticated_select_profiles" ON user_profiles;
CREATE POLICY "authenticated_select_profiles"
  ON user_profiles FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    OR user_id = (SELECT auth.uid())
  );

DROP POLICY IF EXISTS "accessible_programs_select" ON programs;
CREATE POLICY "accessible_programs_select"
  ON programs FOR SELECT TO authenticated
  USING (
    CASE WHEN (SELECT public.is_link_account()) THEN
      slug = ANY((SELECT public.accessible_program_slugs())::text[])
    ELSE
      is_public = true
      OR slug IN (SELECT program_slug FROM user_program_access WHERE user_id = (SELECT auth.uid()))
    END
  );

DROP POLICY IF EXISTS "accessible_fields_select" ON fields;
CREATE POLICY "accessible_fields_select"
  ON fields FOR SELECT TO authenticated
  USING (
    CASE WHEN (SELECT public.is_link_account()) THEN
      name = (SELECT public.link_field())
      AND EXISTS (
        SELECT 1 FROM nircam_images ni
        WHERE ni.field = fields.name
          AND (ni.deploy_status = 'published' OR (SELECT public.link_sees_drafts()))
      )
    ELSE
      EXISTS (
        SELECT 1 FROM nircam_images ni
        WHERE ni.field = fields.name AND ni.deploy_status = 'published'
      )
      OR (SELECT public.is_admin())
    END
  );

DROP POLICY IF EXISTS "accessible_observations_select" ON observations;
CREATE POLICY "accessible_observations_select"
  ON observations FOR SELECT TO authenticated
  USING (
    program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
    AND ((SELECT NOT public.is_link_account())
         OR name = (SELECT public.link_observation()))
  );

DROP POLICY IF EXISTS "select_targets_by_access" ON targets;
CREATE POLICY "select_targets_by_access"
  ON targets FOR SELECT
  USING (
    program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
    -- B1 (#217): hide targets whose only spectra are unpublished. Covers the
    -- target-derived readers that never join spectra (map markers, sed-plot,
    -- /api/targets/[id], tile-thumbnail). Admins see all.
    AND (has_published_spectrum OR (SELECT public.is_admin())
         OR (SELECT public.link_sees_drafts()))
    -- Share links (docs/design-public-mirror.md §5.2): narrow from the whole
    -- program to the one shared observation. accessible_program_slugs() already
    -- pinned a link to its scope's program, but a program can hold many
    -- observations and only one of them was shared.
    AND ((SELECT NOT public.is_link_account())
         OR observation = (SELECT public.link_observation()))
  );

DROP POLICY IF EXISTS "select_objects_by_access" ON objects;
CREATE POLICY "select_objects_by_access"
  ON objects FOR SELECT
  USING (
    programs && (SELECT public.accessible_program_slugs())
    -- B1 (#217): hide objects whose only member spectra are unpublished. Admins
    -- see all. has_published_spectrum is recomputed by reconcile from members.
    AND (has_published_spectrum OR (SELECT public.is_admin())
         OR (SELECT public.link_sees_drafts()))
    -- Share links (docs/design-public-mirror.md §5.2). Array-overlap form: an
    -- object is a cross-observation merge, so it is in scope when the shared
    -- observation is ANY of its members. The object's OTHER members stay hidden
    -- at the target/spectrum level, so a link sees the object as a stub carrying
    -- only its own observation's spectra -- which is the intended behaviour, not
    -- an accident: the colleague sees their reduction of a source, not everyone
    -- else's.
    AND ((SELECT NOT public.is_link_account())
         OR observations && ARRAY[(SELECT public.link_observation())]::text[])
  );

DROP POLICY IF EXISTS "select_object_photometry_by_access" ON object_photometry;
CREATE POLICY "select_object_photometry_by_access"
  ON object_photometry FOR SELECT
  USING (
    object_id IN (
      SELECT o.id FROM objects o
      WHERE o.programs && (SELECT public.accessible_program_slugs())
        -- B1 (#217): no photometry for objects with no published spectrum.
        AND (o.has_published_spectrum OR (SELECT public.is_admin())
             OR (SELECT public.link_sees_drafts()))
        AND ((SELECT NOT public.is_link_account())
             OR o.observations && ARRAY[(SELECT public.link_observation())]::text[])
    )
  );

DROP POLICY IF EXISTS "select_lists" ON object_lists;
CREATE POLICY "select_lists"
  ON object_lists FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    AND id IN (SELECT public.viewable_list_ids())
  );

DROP POLICY IF EXISTS "select_list_members" ON object_list_members;
CREATE POLICY "select_list_members"
  ON object_list_members FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    AND list_id IN (SELECT public.viewable_list_ids())
    AND (
      (object_id IS NULL AND list_id IN (SELECT public.member_editable_list_ids()))
      OR object_id IN (
        SELECT o.id FROM objects o
        WHERE o.programs && (SELECT public.accessible_program_slugs())
          -- B1 (#217): list members matched to an unpublished-only object are
          -- hidden from non-admins (the object itself is invisible).
          AND (o.has_published_spectrum OR (SELECT public.is_admin()))
      )
    )
  );

DROP POLICY IF EXISTS "select_list_audit" ON list_audit_log;
CREATE POLICY "select_list_audit"
  ON list_audit_log FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    AND list_id IN (SELECT public.viewable_list_ids())
  );

DROP POLICY IF EXISTS "select_spectra_by_access" ON spectra;
CREATE POLICY "select_spectra_by_access"
  ON spectra FOR SELECT
  USING (
    target_id IN (
      SELECT t.target_id FROM targets t
      WHERE t.program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
    )
    -- B1 (#217): PRIMARY per-row gate. Only 'published' spectra reach non-admins;
    -- 'draft' and 'revoked' are hidden. This is the sole gate for the user-client
    -- web routes that read spectra directly and never call an RPC (/api/spectrum,
    -- /api/download, /api/redshift-fit, /api/spectrum-thumbnail). Admins see all.
    --
    -- ...and, since share links (docs/design-public-mirror.md §6), an
    -- include_drafts link account -- but only for rows already inside its scope,
    -- which the targets subquery above enforces. 'revoked' stays hidden from
    -- links too: link_sees_drafts() relaxes the gate to draft, never past it.
    AND (deploy_status = 'published' OR (SELECT public.is_admin())
         OR (deploy_status = 'draft' AND (SELECT public.link_sees_drafts())))
  );

DROP POLICY IF EXISTS "select_comments_by_access" ON comments;
CREATE POLICY "select_comments_by_access"
  ON comments FOR SELECT
  USING (
    (SELECT NOT public.is_link_account())
    AND (
      -- Target-level comments
      (target_id IS NOT NULL AND target_id IN (
        SELECT t.id FROM targets t
        WHERE t.program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
          AND (t.has_published_spectrum OR (SELECT public.is_admin()))  -- B1 (#217)
      ))
      OR
      -- Object-level comments
      (target_id IS NULL AND object_id IS NOT NULL AND object_id IN (
        SELECT o.id FROM objects o
        WHERE o.programs && (SELECT public.accessible_program_slugs())
          AND (o.has_published_spectrum OR (SELECT public.is_admin()))  -- B1 (#217)
      ))
    )
  );

DROP POLICY IF EXISTS "select_audit_by_access" ON flag_audit_log;
CREATE POLICY "select_audit_by_access"
  ON flag_audit_log FOR SELECT
  USING (
    (SELECT NOT public.is_link_account())
    AND (
      (target_id IS NOT NULL AND target_id IN (
        SELECT t.id FROM targets t
        WHERE t.program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
          AND (t.has_published_spectrum OR (SELECT public.is_admin()))  -- B1 (#217)
      ))
      OR (object_id IS NOT NULL AND object_id IN (
        SELECT o.id FROM objects o
        WHERE o.programs && (SELECT public.accessible_program_slugs())
          AND (o.has_published_spectrum OR (SELECT public.is_admin()))  -- B1 (#217)
      ))
      OR (spectrum_id IS NOT NULL AND spectrum_id IN (
        SELECT s.id FROM spectra s
        JOIN targets t ON t.target_id = s.target_id
        WHERE t.program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
          AND (s.deploy_status = 'published' OR (SELECT public.is_admin()))  -- B1 (#217)
      ))
    )
  );

DROP POLICY IF EXISTS "authenticated_select_nircam" ON nircam_images;
CREATE POLICY "authenticated_select_nircam"
  ON nircam_images FOR SELECT TO authenticated
  USING (
    CASE WHEN (SELECT public.is_link_account()) THEN
      field = (SELECT public.link_field())
      AND (deploy_status = 'published' OR (SELECT public.link_sees_drafts()))
    ELSE
      deploy_status = 'published' OR (SELECT public.is_admin())
    END
  );

DROP POLICY IF EXISTS "select_storage_objects_by_access" ON storage_objects;
CREATE POLICY "select_storage_objects_by_access"
  ON storage_objects FOR SELECT TO authenticated
  USING (
    status = 'active'
    AND ((SELECT NOT public.is_link_account())
         OR (SELECT public.link_allows_download()))
    AND (
      (storage_objects.spectrum_id IS NOT NULL AND EXISTS (
         SELECT 1 FROM spectra s
         JOIN targets t ON t.target_id = s.target_id
         WHERE s.spectrum_id = storage_objects.spectrum_id
           AND (s.deploy_status = 'published'
                OR (s.deploy_status = 'draft' AND (SELECT public.link_sees_drafts())))
           AND t.program_slug = ANY((SELECT public.accessible_program_slugs())::text[])
           AND ((SELECT NOT public.is_link_account())
                OR t.observation = (SELECT public.link_observation()))))
      OR
      (storage_objects.spectrum_id IS NULL AND storage_objects.deployment_id IS NOT NULL AND EXISTS (
         SELECT 1 FROM deployments d
         LEFT JOIN observations o ON o.name = d.observation
         WHERE d.id = storage_objects.deployment_id
           AND (d.status = 'published'
                OR (d.status = 'draft' AND (SELECT public.link_sees_drafts())))
           AND (
             -- NIRCam field-scoped deploy (epic #261, N1): a field spans multiple
             -- programs, so there is no per-program scope — a published field
             -- deployment is public to everyone. Draft/revoked stay admin-only.
             d.field IS NOT NULL
             OR o.program_slug = ANY((SELECT public.accessible_program_slugs())::text[]))
           AND ((SELECT NOT public.is_link_account())
                OR d.observation = (SELECT public.link_observation())
                OR d.field = (SELECT public.link_field()))))
    )
  );

DROP POLICY IF EXISTS "Authenticated users can read map layers" ON map_layers;
CREATE POLICY "Authenticated users can read map layers"
  ON map_layers FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    OR field = (SELECT public.link_field())
  );

DROP POLICY IF EXISTS "authenticated_select_deployments" ON deployments;
CREATE POLICY "authenticated_select_deployments"
  ON deployments FOR SELECT TO authenticated
  USING (
    (SELECT NOT public.is_link_account())
    OR (
      (
        observation = (SELECT public.link_observation())
        OR field = (SELECT public.link_field())
      )
      AND (status = 'published' OR (SELECT public.link_sees_drafts()))
    )
  );

DROP POLICY IF EXISTS "authenticated_select_fitsgl_datasets" ON fitsgl_datasets;
CREATE POLICY "authenticated_select_fitsgl_datasets"
  ON fitsgl_datasets FOR SELECT TO authenticated
  USING (
    (
      (SELECT NOT public.is_link_account())
      OR field = (SELECT public.link_field())
    )
    AND (
      (SELECT public.is_admin())
      OR public.fitsgl_dataset_is_public(field, tiles, bands, pixel_scale)
    )
  );

DROP POLICY IF EXISTS "Authenticated users can view slit regions" ON slit_regions;
CREATE POLICY "Authenticated users can view slit regions"
  ON slit_regions FOR SELECT TO authenticated
  USING (
    (
      (SELECT NOT public.is_link_account())
      OR observation = (SELECT public.link_observation())
    )
    AND (
      (SELECT public.is_admin())
      OR (SELECT public.link_sees_drafts())
      OR NOT EXISTS (
        SELECT 1 FROM objects o
        WHERE o.object_id = slit_regions.object_id AND o.has_published_spectrum = false
      )
    )
  );

DROP POLICY IF EXISTS "Authenticated users can view shutters" ON shutters;
CREATE POLICY "Authenticated users can view shutters"
  ON shutters FOR SELECT TO authenticated
  USING (
    (
      (SELECT NOT public.is_link_account())
      OR observation = (SELECT public.link_observation())
    )
    AND (
      (SELECT public.is_admin())
      OR (SELECT public.link_sees_drafts())
      OR NOT EXISTS (
        SELECT 1 FROM objects o
        WHERE o.object_id = shutters.object_id AND o.has_published_spectrum = false
      )
    )
  );

DROP POLICY IF EXISTS "admin_manage_share_links" ON share_links;
CREATE POLICY "admin_manage_share_links"
  ON share_links TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));
